version: '3'

services:
  openldap:
    image: docker.io/bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_CUSTOM_LDIF_DIR=/etc/ldif
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - ./org_backup.ldif:/etc/ldif/my_org.ldif
    network_mode: host

volumes:
  openldap_data:
    driver: local


